name: Build and Deploy

on:
  push:
    branches:
      - master
    tags:
      - v0.*
      - v0.*.*
      - v1.*
      - v1.*.*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: deploy
        run: yarn run-s export deploy